# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd38246d990230536c1acd13eb6d5164341679e98697b4b428a059c783a1597e2d9258ed49f9542fdc3a8a2f56204a5bda3809de6edd0bade055e7aefc8da382

test:
  secret_key_base: e0887cdc1a620623129d081f309daadef4fa98fcd15445455dbbd2832f3e27a0aa808371d402216e7877465556e2ec46fd989c0853b2f9aae2fc580bb3a8c677

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
